### ISSUE TITLE
Dealing with empty values

### ISSUE THREAD

**Issue by jtopjian** [puppetlabs/puppetlabs-inifile#40]
Hello,

The puppet openstack modules use the inifile type quite [heavily](https://github.com/stackforge/puppet-glance/blob/master/manifests/api.pp#L96-L104). The basic pattern is that parameters are passed into the module which are then sent to a grouped type to be added to the file.

When setting a value to '', the key is added to the file and the value is empty (which makes logical sense) but upon re-running puppet, the same key is added again so now there are two keys in the file with blank values.

I'm sure empty values break ini file standards, so maybe the best way to handle this is to remove the key from the file when an empty value is given?

This, of course, can be solved with an "ensure => absent" attribute, but in the case of how inifile is being used in the puppet modules, there's no easy way to add this attribute to the grouped inifile resources. We'd have to break each resource out of the grouped resource and apply a parallel "ensure" parameter for the parameter it relates to.

"undef" will simply ignore the resource altogether. This works if the resource was always set to "undef" and you always want to ignore it. But as soon as you give it a non-undef value, you cannot use undef to remove or empty out the value -- undef will continue to ignore the value regardless of what's already in the file.

Please let me know if you need clarification on anything.

Thanks,
Joe

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
