### ISSUE TITLE
using different keyval separators like :

### ISSUE THREAD

**Issue by chandy** [puppetlabs/puppetlabs-inifile#46]
I have a properties file which I would like to manage for my resin application server but the separator is a : rather than a =.  it looks like

app-0.jvm_args: -Xss1m -Xdebug -server -d64 -Xms1024m -Xmx1024m -XX:NewSize=256m -XX:MaxNewSize=256m -XX:MaxPermSize=256m

So I thought the ini_subsetting type would be great for adding in extra params like -XX:MaxPermSize=256m to the line but in testing it always looks for a = and i guess keyval separator is more meant for dealing with whitespaces than other separators.  I was wondering if this is something you would be implementing in the future, or if maybe i can create a child class to change the separator, or maybe if there is another puppet module more suitable for managing this type of resource?  Thanks :)

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
