### ISSUE TITLE
stdlib 9.x.x compat

### ISSUE THREAD

**Issue by jcpunk** [puppetlabs/puppetlabs-inifile#513]
**Is your feature request related to a problem? Please describe.**
With the new release of stdlib 9.x, the module dependencies should be updated

**Describe the solution you'd like**
Compatibility with stdlib 9.x

**Describe alternatives you've considered**
Staying locked at an older version

**Additional context**
https://forge.puppet.com/modules/puppetlabs/stdlib/changelog

**Comment by jordanbreen28** [comment]
Hey @jcpunk - we are in the process of rolling the puppetlabs/stdlib bump to all our supported modules and this will be completed by COB tomorrow.
