### ISSUE TITLE
data not written to ini file on amazon linux

### ISSUE THREAD

**Issue by tlipatov** [puppetlabs/puppetlabs-inifile#57]
Hello, not sure what the underlying issue is, looking for guidance to troubleshooting this.

When running ini_setting on amazon linux, nothing is being written to the specified ini file.

[root@ip tmp]# cat test.pp 

ini_setting { "sample setting":
  path    => '/tmp/foo.ini',
  section => 'foo',
  setting => 'foosetting',
  value   => 'FOO!',
  ensure  => present,
}

[root@ip tmp]# puppet apply test.pp 
notice: Finished catalog run in 0.08 seconds
cat /tmp/foo.ini
[root@ip tmp]#

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
