### ISSUE TITLE
Enhancement:  Support adding comments above ini_setting

### ISSUE THREAD

**Issue by rbeede** [puppetlabs/puppetlabs-inifile#72]
It'd be nice to have a comment => 'some comment here' option that adds a comment right above the ini_setting.

```
  ini_setting { 'example of comment feature':
    ensure  => 'present',
    path    => '/etc/some.conf',
    section => 'CoolSection',
    setting => 'HandyKey',
    value   => 'UsefulValue',
    comment => 'This setting allows for blah blah blah'
  }
```

This would result in:

```
[CoolSection]
# This setting allows for blah blah blah
HandyKey = UsefulValue
```

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
