### ISSUE TITLE
The 1.0.1 tarball on the forge is dirty

### ISSUE THREAD

**Issue by ssm** [puppetlabs/puppetlabs-inifile#76]
The 1.0.1 tarball downloadable from the puppet forge contains the files:

```
lib/puppet/provider/ini_setting/.ruby.rb.swp
lib/puppet/provider/ini_subsetting/.ruby.rb.swp
lib/puppet/type/.ini_setting.rb.swp
lib/puppet/type/.ini_subsetting.rb.swp
lib/puppet/util/.setting_value.rb.swp
spec/acceptance/.ini_setting_spec.rb.swp
spec/acceptance/.ini_subsetting_spec.rb.swp
```

Please look at using something like 

```
git archive --prefix=puppetlabs-inifile-$version --format=tar \
  --output=puppetlabs-inifile-$version HEAD
```

…to build packages.  That way, you don't get a dirty tarball when the working directory is not clean.

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
